package co.edu.usbcali.modelo;
// Generated 03-jun-2018 13:45:35 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Almuerzo generated by hbm2java
 */
public class Almuerzo implements java.io.Serializable {

	private BigDecimal id;
	private Bebida bebida;
	private Hijo hijo;
	private Pedido pedido;
	private Principio principio;
	private Proteina proteina;
	private Sopa sopa;
	private String dia;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModifica;
	private Date fechaModifica;

	public Almuerzo() {
	}

	public Almuerzo(BigDecimal id, Hijo hijo, Pedido pedido, String dia) {
		this.id = id;
		this.hijo = hijo;
		this.pedido = pedido;
		this.dia = dia;
	}

	public Almuerzo(BigDecimal id, Bebida bebida, Hijo hijo, Pedido pedido, Principio principio, Proteina proteina,
			Sopa sopa, String dia, Integer estado, String usuarioCreacion, Date fechaCreacion, String usuarioModifica,
			Date fechaModifica) {
		this.id = id;
		this.bebida = bebida;
		this.hijo = hijo;
		this.pedido = pedido;
		this.principio = principio;
		this.proteina = proteina;
		this.sopa = sopa;
		this.dia = dia;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Bebida getBebida() {
		return this.bebida;
	}

	public void setBebida(Bebida bebida) {
		this.bebida = bebida;
	}

	public Hijo getHijo() {
		return this.hijo;
	}

	public void setHijo(Hijo hijo) {
		this.hijo = hijo;
	}

	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public Principio getPrincipio() {
		return this.principio;
	}

	public void setPrincipio(Principio principio) {
		this.principio = principio;
	}

	public Proteina getProteina() {
		return this.proteina;
	}

	public void setProteina(Proteina proteina) {
		this.proteina = proteina;
	}

	public Sopa getSopa() {
		return this.sopa;
	}

	public void setSopa(Sopa sopa) {
		this.sopa = sopa;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

}
