package co.edu.usbcali.modelo;
// Generated 03-jun-2018 13:45:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Padre generated by hbm2java
 */
public class Padre implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private String telefono;
	private String direccion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModifica;
	private Date fechaModifica;
	private Set<Hijo> hijos = new HashSet<Hijo>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Padre() {
	}

	public Padre(long id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Padre(long id, Usuario usuario, String telefono, String direccion, String usuarioCreacion,
			Date fechaCreacion, String usuarioModifica, Date fechaModifica, Set<Hijo> hijos, Set<Pedido> pedidos) {
		this.id = id;
		this.usuario = usuario;
		this.telefono = telefono;
		this.direccion = direccion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.hijos = hijos;
		this.pedidos = pedidos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public Set<Hijo> getHijos() {
		return this.hijos;
	}

	public void setHijos(Set<Hijo> hijos) {
		this.hijos = hijos;
	}

	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
